package com.skillassessment.platform.dto;

import com.skillassessment.platform.enums.DifficultyLevel;
import com.skillassessment.platform.enums.ItProfile;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data Transfer Object for requesting an AI-generated quiz.
 * This class is used as the request body for the AI quiz generation endpoint.
 * It includes validation rules to ensure the parameters are valid.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class AiGenerateQuizRequestDto {

    /**
     * The IT profile or technology domain for the quiz.
     * Cannot be null.
     */
    @NotNull(message = "IT profile cannot be null")
    private ItProfile itProfile;

    /**
     * The desired difficulty level for the quiz.
     * Cannot be null.
     */
    @NotNull(message = "Difficulty level cannot be null")
    private DifficultyLevel difficultyLevel;

    /**
     * The number of questions to be generated by the AI.
     * Must be between 5 and 50 to ensure meaningful quizzes and manage API costs.
     */
    @Min(value = 5, message = "Number of questions must be at least 5")
    @Max(value = 50, message = "Number of questions cannot exceed 50")
    private int numberOfQuestions;
}