package com.skillassessment.platform.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Data Transfer Object for representing a detailed quiz attempt.
 * This DTO is used to return a full report to the user, including their score,
 * AI-generated feedback, and a breakdown of their answers.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class QuizAttemptDto {

    /**
     * The unique identifier for this specific quiz attempt.
     */
    private Long id;

    /**
     * The ID of the user who took the quiz.
     */
    private Long userId;

    /**
     * The ID of the quiz that was attempted.
     */
    private Long quizId;

    /**
     * The raw score (number of correctly answered questions).
     */
    private Double score;

    /**
     * The score as a percentage (0-100).
     */
    private Double percentage;

    /**
     * The timestamp when the quiz attempt was started.
     */
    private LocalDateTime startedAt;

    /**
     * The timestamp when the quiz attempt was completed and submitted.
     */
    private LocalDateTime completedAt;

    /**
     * The total time taken to complete the quiz, in seconds.
     */
    private Long timeTakenSeconds;

    /**
     * A JSON string containing the detailed performance report generated by the AI.
     * The frontend is expected to parse this string into a JSON object.
     */
    private String detailedReportJson;

    /**
     * A JSON string containing the personalized study plan generated by the AI.
     * The frontend is expected to parse this string into a JSON object.
     */
    private String studyPlanJson;

    /**
     * A detailed list of each answer submitted by the user.
     */
    private List<AttemptAnswerDto> answers;


    /**
     * A nested DTO to represent the details of a single answered question within an attempt.
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public static class AttemptAnswerDto {
        private Long questionId;
        private String questionText;
        private Character submittedOption;
        private Character correctOption;
        private boolean isCorrect;
        private String explanation; // Explanation for the correct answer
    }
}